/*
 * Smobilpay S3P API
 * Smobilpay Third Party API FOR PAYMENT COLLECTIONS
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.afriland.afbpaypartnerservices.models;

import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
/**
 * Quote
 */
@ToString
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Quote {
  
	private String quoteId;
	private Date expiresAt;
	private String payItemId;
	private Double amountLocalCur;
	private Integer priceLocalCur;
	private Integer priceSystemCur;
	private String localCur;
	private String systemCur;
	private Object promotion;
	/**
	 * @return the quoteId
	 */
	public String getQuoteId() {
		return quoteId;
	}
	/**
	 * @param quoteId the quoteId to set
	 */
	public void setQuoteId(String quoteId) {
		this.quoteId = quoteId;
	}
	/**
	 * @return the expiresAt
	 */
	public Date getExpiresAt() {
		return expiresAt;
	}
	/**
	 * @param expiresAt the expiresAt to set
	 */
	public void setExpiresAt(Date expiresAt) {
		this.expiresAt = expiresAt;
	}
	/**
	 * @return the payItemId
	 */
	public String getPayItemId() {
		return payItemId;
	}
	/**
	 * @param payItemId the payItemId to set
	 */
	public void setPayItemId(String payItemId) {
		this.payItemId = payItemId;
	}
	/**
	 * @return the amountLocalCur
	 */
	public Double getAmountLocalCur() {
		return amountLocalCur;
	}
	/**
	 * @param amountLocalCur the amountLocalCur to set
	 */
	public void setAmountLocalCur(Double amountLocalCur) {
		this.amountLocalCur = amountLocalCur;
	}
	/**
	 * @return the priceLocalCur
	 */
	public Integer getPriceLocalCur() {
		return priceLocalCur;
	}
	/**
	 * @param priceLocalCur the priceLocalCur to set
	 */
	public void setPriceLocalCur(Integer priceLocalCur) {
		this.priceLocalCur = priceLocalCur;
	}
	/**
	 * @return the priceSystemCur
	 */
	public Integer getPriceSystemCur() {
		return priceSystemCur;
	}
	/**
	 * @param priceSystemCur the priceSystemCur to set
	 */
	public void setPriceSystemCur(Integer priceSystemCur) {
		this.priceSystemCur = priceSystemCur;
	}
	/**
	 * @return the localCur
	 */
	public String getLocalCur() {
		return localCur;
	}
	/**
	 * @param localCur the localCur to set
	 */
	public void setLocalCur(String localCur) {
		this.localCur = localCur;
	}
	/**
	 * @return the systemCur
	 */
	public String getSystemCur() {
		return systemCur;
	}
	/**
	 * @param systemCur the systemCur to set
	 */
	public void setSystemCur(String systemCur) {
		this.systemCur = systemCur;
	}
	/**
	 * @return the promotion
	 */
	public Object getPromotion() {
		return promotion;
	}
	/**
	 * @param promotion the promotion to set
	 */
	public void setPromotion(Object promotion) {
		this.promotion = promotion;
	}


}
